dc_311_data_api_endpoints:
  2021: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/12/query"
  2022: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/14/query"
  2023: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/15/query"
  2024: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/16/query"
  
api_query_parameters:
  where: "1=1"
  outFields: "*"
  f: "json"
  resultRecordCount: 1000
  resultOffset: 0

# Max number of records to extract. When this value is negative, we extract
# the max possible number of records.
max_num_records: -999

features:
  - ward
  - servicecode
  - adddate

# Target values less than or equal to this value are set to 0
# Greater than this value are set to 1
target_threshold: 21

# Assign years to training, validation, and test sets
train_year:
  - 2021
  - 2022
validation_year:
  - 2023
test_year:
  - 2024

# Modeling hyperparameters
tracking_uri: data/mlruns
experiment_name: xgb_pca_model_2
n_trials: 100
model_type: xgboost     # logistic or xgboost
pca: true     # true or false
random_seed: 123
ranges:
  logreg_c:
    min: 1.0e-10
    max: 1.0e10
  pca_n_components:
    min: 1
  xgb_max_depth:
    min: 3
    max: 10
  xgb_n_estimators:
    min: 50
    max: 1000
  xgb_learning_rate:
    min: 1.0e-4
    max: 0.3
