dc_311_data_api_endpoints:
  2021: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/12/query"
  2022: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/14/query"
  2023: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/15/query"
  
api_query_parameters:
  where: "1=1"
  outFields: "*"
  f: "json"
  resultRecordCount: 1000
  resultOffset: 0

# Max number of records to extract. When this value is negative, we extract
# the max possible number of records.
max_num_records: -999

features:
  - ward
  - servicecode
  - adddate

# Assign years to training, validation, and test sets
train_year:
  - 2021
  - 2022
validation_year:
  - 2023
test_year:
  - 2024

# Modeling hyperparameters
tracking_uri: data/mlruns
experiment_name: experiment_testing
n_trials: 4
model_type: logistic
pca: true
