dc_311_data_api_endpoints:
  2021: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/12/query"
  2022: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/14/query"
  2023: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/15/query"
  2024: "https://maps2.dcgis.dc.gov/dcgis/rest/services/\
    DCGIS_DATA/ServiceRequests/FeatureServer/16/query"
  
api_query_parameters:
  where: "1=1"
  outFields: "*"
  f: "json"
  resultRecordCount: 1000
  resultOffset: 0

# Max number of records to extract. When this value is negative, we extract
# the max possible number of records.
max_num_records: -999

# Features to include in model
features:
  - ward
  - servicecode
  - adddate

# Target values less than or equal to this value are set to 0
# Greater than this value are set to 1
target_threshold: 4

# Assign years to training, validation, and test sets
train_year:
  - 2021
  - 2022
validation_year:
  - 2023
test_year:
  - 2024

# Modeling hyperparameters
task_type: classification   # regression or classification
tracking_uri: data/mlruns   # Local folder where mlflow files are saved
experiment_name: reg_en     # Name of mlflow experiment (can be anything)
n_trials: 5                 # Number of optuna trials during model training
model_type: logistic        # logistic, xgboost, or elasticnet
pca: false                  # true or false (whether to include PCA in model pipeline)
random_seed: 123            # for reproducibility
ranges:                     # Hyperparameter ranges for optuna. Prefix is the model type.
  logreg_c:
    min: 1.0e-10
    max: 1.0e10
  pca_n_components:
    min: 1
  xgb_max_depth:
    min: 3
    max: 10
  xgb_n_estimators:
    min: 50
    max: 1000
  xgb_learning_rate:
    min: 1.0e-4
    max: 0.3
  en_alpha:
    min: 0
    max: 0.5
  en_l1_ratio:
    min: 0.9
    max: 1.0
